version: '3'
services:
  api:
    image:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - users
      - orders
  users:
    build: ./users
    depends_on:
      - db
  orders:
    build: ./orders
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Akan
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
